[build]
  publish = "public"
  command = "gatsby info && gatsby build"
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "10.16.0"
  YARN_VERSION = "1.16.0"
  YARN_FLAGS = "--no-ignore-optional"
